@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}
class FetchDriver extends Configured implements Tool {
List list;
ArrayList l;
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml